### PR TITLE
Fix namespaced qnames

### PR DESCRIPTION
**Pull request by joewiz**
Fixes issue described at http://markmail.org/message/f6qfy6ll7qqyh5de. Fix partially outlined at https://github.com/eXist-db/exist/issues/792.

### CODE REVIEW

**Comment by joewiz** [comment]
Fixes https://github.com/eXist-db/exist/issues/792.

**Comment by wolfgangmm** [comment]
ok, looks like the main fix is:

```xquery
let $uri := (namespace-uri-for-prefix($name, $xconf/cc:collection), namespace-uri-for-prefix($name, $xconf//cc:index))[1]
```

which seems correct, because namespace-uri-for-prefix may return a namespace for both, cc:collection and cc:index.

**Comment by joewiz** [comment]
@wolfgangmm Thanks for the quick merge.

@jensopetersen I agree with @wolfgangmm's take on why the `[1]` was necessary here. What I haven't been able to track down is why we had to apply the same `[1]` to the results of `request:get-parameter()`, as in https://github.com/wolfgangmm/monex/pull/13/files#diff-7d9dd51bcbb3faaf04ffca2fae9f2c2fR785. Perhaps my parameter-related functions produced duplicates. I'm happy to take a look at other cases if we feel these are causing problems.

My sense of what's most needed to advance the indexes page is to add more test data to https://github.com/wolfgangmm/monex/blob/master/indexes-test/data/indexes-test-data.xml so that we can clearly identify areas where the index browser is failing to display results. This might be a good way to illustrate indexing-related issues such as https://github.com/eXist-db/exist/issues/794 and https://github.com/eXist-db/exist/issues/795.

**Comment by jensopetersen** [comment]
Sorry @joewiz, I guess I was feeling bad about the ad hoc nature of my own "fix" and let it spill over here. I see that this solves the problem at the root. I will check if any of the other "fixes" are rendered unnecessary by it.

**Comment by joewiz** [comment]
Closes https://github.com/eXist-db/exist/issues/792.

**Pull request merged**
